/**
 * ====================================================================
 * Data Layer - 只存储数据，不包含渲染逻辑
 * ====================================================================
 */
const articlesData = [
    {
        id: 25,
        title: "GC怎么保证不 STW 的？（二）",
        summary: "本章节我们主要去阐述，ZGC 的并发整理是怎么实现的，这里主要解决的问题是怎么实现一个对象被移动后（标记-复制），移动到一个新的 Region，我们还能正常的访问的到。",
        link: "https://mp.weixin.qq.com/s/hHZseg7QYVk4iNeuvkbOhg",
        platform: "微信公众号",
        date: "2025-07-30",
        mainCategory: "Java",
        subCategory: "JVM 虚拟机",
        featured: true,
        isResearch: false
    },
    {
        id: 24,
        title: "GC怎么保证不 STW 的？（一）",
        summary: "保证不 STW，本质是个并发问题，怎么保证用户线程和垃圾回收线程互不干扰的运行，这里就提出了三点要求：...",
        link: "https://mp.weixin.qq.com/s/iOdbzOu9aKdR62LPtROEkg",
        platform: "微信公众号",
        date: "2025-06-25",
        mainCategory: "Java",
        subCategory: "JVM 虚拟机",
        featured: true,
        isResearch: false
    },
    {
        id: 23,
        title: "LLM 推理成本直降 90% 应用提速 85%：提示词缓存如何重塑 Agent 开发",
        summary: "本文旨在详细阐述“提示词缓存”（Prompt Caching）技术。为确保内容的清晰与循序渐进，文章将 ：首先介绍其基本定义、核心机制及其收益，再讲述其在 Agent 开发中如何落地",
        link: "https://mp.weixin.qq.com/s/xfidMN73XnurT0O-OrpWPg",
        platform: "微信公众号",
        date: "2025-07-30",
        mainCategory: "人工智能",
        subCategory: "工程开发",
        featured: true,
        isResearch: false
    },
    {
        id: 22,
        title: "AI 工程专业术语扫盲",
        summary: "作为开发者，我们主要将目光聚焦于 Agent、MCP，Function call、RAG等概念，我们对这些概念进行扫盲，让在开发沟通中减少阻碍",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lagatg/srhewvsgvcswyds8?singleDoc# 《AI 工程专业术语扫盲【未完待续】》",
        platform: "语雀",
        date: "2025-05-07",
        mainCategory: "人工智能",
        subCategory: "工程开发",
        featured: true,
        isResearch: true
    },
    {
        id: 21,
        title: "GFS（3）- 大数据的三驾马车",
        summary: "GFS 也就是 Google 文件系统。目前的大部分分布式系统都或多或少的依赖于底层的文件系统。",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lagatg/cg6disr86tugih9p?singleDoc# 《GFS（3）- 大数据的三驾马车》",
        platform: "语雀",
        date: "2025-05-05",
        mainCategory: "大数据",
        subCategory: "经典论文",
        featured: false,
        isResearch: true
    },
    {
        id: 20,
        title: "GFS（2）- 大数据的三驾马车",
        summary: "GFS 也就是 Google 文件系统。目前的大部分分布式系统都或多或少的依赖于底层的文件系统。",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lagatg/ggru1bz14yr7vzw6?singleDoc# 《GFS（2）- 大数据的三驾马车》",
        platform: "语雀",
        date: "2025-05-03",
        mainCategory: "大数据",
        subCategory: "经典论文",
        featured: false,
        isResearch: true
    },
    {
        id: 19,
        title: "GFS（1）- 大数据的三驾马车",
        summary: "GFS 也就是 Google 文件系统。目前的大部分分布式系统都或多或少的依赖于底层的文件系统。",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lagatg/gx2szi2mss9pkbps?singleDoc# 《GFS（1）- 大数据的三驾马车》",
        platform: "语雀",
        date: "2025-05-01",
        mainCategory: "大数据",
        subCategory: "经典论文",
        featured: false,
        isResearch: true
    },
    {
        id: 18,
        title: "有了MESI缓存一致性协议为什么还需要volatile？",
        summary: "本篇文章先从 CPU 的三级缓存讲起，再讲解三级缓存带来的缓存不一致的挑战，最后去讲解 Java 中的volatile...",
        link: "https://mp.weixin.qq.com/s/50wt85WcCmdmIQY--sVVBw",
        platform: "微信公众号",
        date: "2025-04-25",
        mainCategory: "Java",
        subCategory: "Java并发",
        featured: true,
        isResearch: false
    },
    {
        id: 16,
        title: "论文速读 - DeepSeek OCR",
        summary: "当前的大语言模型 (LLM) 面临一个普遍的挑战：随着处理的文本序列越来越长，其计算和内存成本会呈平方级增长 。这使得它们在处理整本书、长篇报告或漫长的对话历史时不堪重负。\n" +
            "\n" +
            "为应对这一难题，DeepSeek-OCR 提出了一种新方法：不再逐字“阅读”文本，而是通过“看图”的方式来高效压缩和处理长上下文。",
        link: "https://mp.weixin.qq.com/s/DZiS26gMiqKxgLXarBLp5Q",
        platform: "微信公众号",
        date: "2025-10-24",
        mainCategory: "人工智能",
        subCategory: "AI论文简报",
        featured: true,
        isResearch: true
    },
    {
        id: 15,
        title: "Tracing the thoughts of a large language model",
        summary: "这篇论文主要阐述了 Anthropic 科学家如何追踪大语言模型（LLM）的思考过程。具体来说，就是当模型接收到一个提示词后，其内部神经元是如何运作的。",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lagatg/qgwoqmmqrinck1i0?singleDoc# 《Tracing the thoughts of a large language model》",
        platform: "语雀",
        date: "2025-04-01",
        mainCategory: "人工智能",
        subCategory: "经典论文",
        featured: true,
        isResearch: true
    },
    {
        id: 6,
        title: "Java线程池如何保证线程安全？",
        summary: "在Java并发编程中，ThreadPoolExecutor类号称线程池的\"大脑\"，Java线程池的线程安全设计展示了并发编程的终极艺术。",
        link: "https://juejin.cn/post/7490497276738486322",
        platform: "掘金",
        date: "2025-04-08",
        mainCategory: "Java",
        subCategory: "Java并发",
        featured: true,
        isResearch: false
    },
    {
        id: 7,
        title: "《Computer Networking A Top-Down Approach》- 拥塞控制原理与TCP拥塞",
        summary: "探讨网络拥塞控制的基本原理以及 TCP 协议如何实现拥塞控制。",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lagatg/kkmagdynt183fyvo",
        platform: "语雀",
        date: "2025-04-01",
        mainCategory: "计算机网络",
        subCategory: "TCP",
        featured: false,
        isResearch: true
    },
    {
        id: 14,
        title: "操作系统 - PageTable（一）",
        summary: "这篇文章主要探讨了操作系统中的页表相关内容，包括页表如何为进程提供专用空间和地址，实现地址转换与隔离。",
        link: "https://juejin.cn/post/7477228933638373391",
        platform: "掘金",
        date: "2025-03-03",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: true,
        isResearch: false
    },
    {
        id: 5,
        title: "操作系统 - 中断与系统驱动",
        summary: "网卡收到 pack page,网卡就会产生中断，按下键盘也会产生中断。如果受到一个中断，sw save its work, process interupt, resume its work。",
        link: "https://juejin.cn/spost/7485188648485601280",
        platform: "掘金",
        date: "2025-03-24",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: true,
        isResearch: false
    },
    {
        id: 4,
        title: "MIT6.1810 - 结构与组织",
        summary: "这篇文章主要介绍了操作系统的结构与组织，包括操作系统的经典组织结构，如硬件资源、内核空间和用户空间的关系，内核中的重要模块...",
        link: "https://juejin.cn/post/7474427694630142002",
        platform: "掘金",
        date: "2025-02-23",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: false,
        isResearch: true
    },
    {
        id: 3,
        title: "操作系统-NetWorking",
        summary: "文章主要围绕操作系统中的网络功能展开，包括网络分类及通信方式、重要协议（以太网、ARP、IP、UDP）等内容。",
        link: "https://juejin.cn/post/7473721599248744485",
        platform: "掘金",
        date: "2025-02-21",
        mainCategory: "操作系统",
        subCategory: "网络基础",
        featured: false,
        isResearch: false
    },
    {
        id: 13,
        title: "MIT6.1810 - Sleep And Wake Up（1）",
        summary: "介绍 xv6 操作系统中进程睡眠与唤醒机制的基本原理和实现。",
        link: "https://mp.weixin.qq.com/s/NeaYy0R4gXtEDpz0nVYU1w",
        platform: "微信公众号",
        date: "2024-12-29",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: false,
        isResearch: true
    },
    {
        id: 12,
        title: "MIT6.1810 - Sleep And Wake Up（2）",
        summary: "深入探讨 xv6 中睡眠与唤醒的锁机制和 lost wake-up 问题。",
        link: "https://mp.weixin.qq.com/s/Ksen60Ki0wwrSFtdMnVBaw",
        platform: "微信公众号",
        date: "2024-12-29",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: false,
        isResearch: true
    },
    {
        id: 11,
        title: "MIT6.1810 - Scheduler And Thread Switch",
        summary: "讲解 xv6 的调度器实现以及线程切换的过程。",
        link: "https://mp.weixin.qq.com/s/28YhnpgXE_vD3dOTiYYNQg",
        platform: "微信公众号",
        date: "2024-12-28",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: false,
        isResearch: true
    },
    {
        id: 10,
        title: "MIT6.1810 - Copy On Write",
        summary: "介绍写时复制（Copy On Write）技术在 xv6 中的应用。",
        link: "https://mp.weixin.qq.com/s/SgW_RtLbvu0UjHX_hTsFBg",
        platform: "微信公众号",
        date: "2024-12-28",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: false,
        isResearch: true
    },
    {
        id: 8,
        title: "MIT6.1810 - Operation System Organization",
        summary: "概述操作系统的基本组织结构和 xv6 的设计。",
        link: "https://mp.weixin.qq.com/s/sCAaLyMUnBGC4rKOBN90mA",
        platform: "微信公众号",
        date: "2024-12-28",
        mainCategory: "操作系统",
        subCategory: "MIT6.1810【笔记】",
        featured: false,
        isResearch: true
    },
    {
        id: 201,
        title: "MySQL - 查询篇",
        summary: "文章主要围绕 MySQL 中的查询篇展开，深入讲解查询语句的使用技巧、优化方法等...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/cwcgubokz1hblvw5?singleDoc# 《查询篇》",
        platform: "语雀",
        date: "2025-02-11",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 202,
        title: "MySQL - 存储引擎篇",
        summary: "文章主要围绕MySQL中的存储引擎篇展开...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/yxqxpt0858ngqpe9?singleDoc# 《存储引擎篇》",
        platform: "语雀",
        date: "2025-02-10",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 203,
        title: "MySQL - 缓存篇",
        summary: "文章聚焦于 MySQL 中的缓存篇，详细介绍缓存机制、缓存策略以及如何有效利用缓存提升性能...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/yxqxpt0858ngqpe9?singleDoc# 《缓存篇》",
        platform: "语雀",
        date: "2025-02-12",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 204,
        title: "MySQL - 索引篇",
        summary: "文章着重介绍 MySQL 中的索引篇，包括索引的类型、创建和使用索引的注意事项以及索引对查询性能的影响...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/ttq528fb1bza7o34?singleDoc# 《索引篇》",
        platform: "语雀",
        date: "2025-02-14",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 205,
        title: "MySQL-MVCC 篇",
        summary: "该文章深入剖析 MySQL 中的 MVCC 篇，详细讲解 MVCC 的工作原理、实现机制以及在并发控制中的应用...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/egmggw9ld3fmoiin?singleDoc# 《MVCC篇》",
        platform: "语雀",
        date: "2025-02-15",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 206,
        title: "MySQL - 锁篇",
        summary: "文章主要针对 MySQL 中的锁篇，全面介绍锁的类型、锁的粒度以及如何避免死锁等问题...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/frd4zmhhvz6mzmqz?singleDoc# 《锁篇》",
        platform: "语雀",
        date: "2025-02-16",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 207,
        title: "MySQL - 实践开发篇",
        summary: "此文章围绕 MySQL 在实践开发中的应用展开，分享实际项目中使用 MySQL 的经验、技巧以及常见问题的解决方案...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/gihgg9agt8nhe2bu?singleDoc# 《实践开发篇》",
        platform: "语雀",
        date: "2025-02-17",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 208,
        title: "MySQL - 优化篇",
        summary: "该文章围绕 MySQL 的优化篇，从多个方面介绍优化策略，包括查询优化、存储优化、服务器参数优化等...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/mqzyghdezlgkkmh7?singleDoc# 《优化篇》",
        platform: "语雀",
        date: "2025-02-19",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 209,
        title: "MySQL - 问答篇",
        summary: "文章以问答形式呈现，涵盖 MySQL 使用过程中的常见问题及详细解答，为读者提供实用的参考...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/tqi51k3apvv80b71?singleDoc# 《问答篇》",
        platform: "语雀",
        date: "2025-02-20",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 210,
        title: "MySQL - 日志篇",
        summary: "此文章围绕 MySQL 中的日志篇，全面阐述日志类型、日志记录原理以及日志在故障排查和数据恢复中的作用...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/xbdexw8q18ugtll8?singleDoc# 《日志篇》",
        platform: "语雀",
        date: "2024-09-13",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    },
    {
        id: 211,
        title: "MySQL - 架构篇",
        summary: "文章聚焦于 MySQL 的架构篇，详细解读 MySQL 的体系架构、各个组件的功能以及架构设计的要点...",
        link: "https://www.yuque.com/yuqueyonghu6p3x1u/lau566/zgkvm3dydayfgf7q?singleDoc# 《架构篇》",
        platform: "语雀",
        date: "2024-10-18",
        mainCategory: "数据库",
        subCategory: "MySQL 学习笔记",
        featured: false,
        isResearch: true
    }
];